# Generated by Django 6.0 on 2025-12-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='creaed_at',
            new_name='created_at',
        ),
    ]
